### ISSUE TITLE
Scrape Trending Section

### ISSUE THREAD

**Issue by bugbreaker18** [bugbreaker18/AniwatchScrape#1]
Create a new google sheet and an appscript 'script' for scraping the contents of the trending section in Aniwatch website. convert it to json using the script that was previously made and push the data to MongoDB.

**Comment by Bhargav-44** [comment]
Okay sir!

**Comment by bugbreaker18** [comment]
> So for trending we need img, name and order right?

yes. do not push to MongoDB for now.
